### ISSUE TITLE
To-do's - Index page

### ISSUE THREAD

**Issue by jjhonson** [jjhonson/nicolejhonson.com#1]
- [X] Put a favicon on the page
- [ ] Sharpen up the brand logo - its a bit fuzzy now
- [ ] Make the phone number clickable - should dial the number on a mobile device
- [ ] Contact button should be more prominent
- [ ] Add all of the external tools (google analytics, etc.) from the old site to the new one
- [ ] Change the top horizontal image - either to the original or something better
- [ ] Spread out and enlarge the words on the navbar
- [ ] Have a look to see if a color background behind the middle content looks good (like the old site)
- [ ] Fix the styling, spacing and placement of the "learn more" and "request" buttons at the bottom of the page
- [ ] Add links to appropriate pages in the body copy at the bottom of the page
- [ ] Add links from cities in the middle section to appropriate pages
- [ ] Add a footer
- [ ] Link email address to open a new email
